// Submits Incident Reports (IR-01) and Daily Activity Logs (DA-02).
// v3 changes:
//  - Officer session is verified; the verified identity is recorded on the
//    report so submissions cannot be spoofed once Auth0 is enabled.
//  - Report numbers (PHS-#### / DAR-####) are generated by Apps Script with
//    a lock, never here, so numbers are sequential and collision-free.
//  - Attachments arrive inline (small files) or as chunk references (large
//    files uploaded through /api/upload-chunk).

import crypto from "node:crypto";
import path from "node:path";
import { json, getBackendConfig, requireOfficer, getStore, errorResponse } from "./lib/shared.mjs";

const MAX_FILE_BYTES = 50 * 1024 * 1024;
const MAX_INLINE_BYTES = 3 * 1024 * 1024;
const UPLOAD_ID_PATTERN = /^[a-f0-9-]{36}$/;

function safeName(name) {
  const parsed = path.basename(String(name || "attachment"));
  return parsed.replace(/[^a-zA-Z0-9._ -]/g, "_").slice(0, 120) || "attachment";
}

function getBaseUrl(request) {
  const url = new URL(request.url);
  return `${url.protocol}//${url.host}`;
}

function validatePayload(incoming) {
  if (!incoming.submittedBy) throw new Error("Missing required field: submittedBy");
  if (!incoming.campus) throw new Error("Missing required field: campus");
  if (!incoming.location) throw new Error("Missing required field: location");
  if (!incoming.dateOfIncident) throw new Error("Missing required field: dateOfIncident");
  if (!incoming.timeOfIncident) throw new Error("Missing required field: timeOfIncident");
  if (!incoming.summary) throw new Error("Missing required field: summary");

  if (incoming.reportType === "daily_activity") {
    if (!incoming.activityType) throw new Error("Missing required field: activityType");
  } else {
    if (!incoming.reportType) throw new Error("Missing required field: reportType");
    if (!incoming.priority) throw new Error("Missing required field: priority");
    if (!incoming.peopleInvolvedChoice) throw new Error("Missing required field: peopleInvolvedChoice");
    if (incoming.peopleInvolvedChoice === "Yes" && !incoming.peopleInvolved) {
      throw new Error("Missing required field: peopleInvolved");
    }
    if (!incoming.actionTaken) throw new Error("Missing required field: actionTaken");
  }
}

async function saveAttachments(request, submissionKey, attachments) {
  if (!Array.isArray(attachments) || !attachments.length) return [];

  const store = await getStore("report-attachments");
  const baseUrl = getBaseUrl(request);
  const saved = [];

  for (let i = 0; i < attachments.length; i++) {
    const file = attachments[i];
    const name = safeName(file.name);
    const declaredSize = Number(file.size || 0);
    if (declaredSize > MAX_FILE_BYTES) {
      throw new Error(`${name} is too large. Maximum file size is 50 MB.`);
    }

    const accessToken = crypto.randomUUID();
    const key = `${submissionKey}/${String(i + 1).padStart(2, "0")}-${crypto.randomUUID()}-${name}`;

    if (file.uploadId) {
      // Large file: chunks already sit in Blobs. Store a manifest that the
      // download function reassembles into a single streamed response.
      const uploadId = String(file.uploadId);
      const parts = Number(file.parts);
      if (!UPLOAD_ID_PATTERN.test(uploadId)) throw new Error(`Upload reference for ${name} is invalid.`);
      if (!Number.isInteger(parts) || parts < 1 || parts > 20) throw new Error(`Chunk count for ${name} is invalid.`);

      const chunkKeys = [];
      let totalBytes = 0;

      for (let part = 0; part < parts; part++) {
        const chunkKey = `chunks/${uploadId}/${String(part).padStart(3, "0")}`;
        const meta = await store.getMetadata(chunkKey);
        if (!meta) throw new Error(`${name} did not finish uploading. Try again.`);
        totalBytes += Number(meta.metadata?.size || 0);
        chunkKeys.push(chunkKey);
      }

      if (totalBytes > MAX_FILE_BYTES) throw new Error(`${name} is too large. Maximum file size is 50 MB.`);

      await store.setJSON(key, { chunkKeys }, {
        metadata: {
          accessToken,
          chunked: true,
          name,
          type: file.type || "application/octet-stream",
          size: totalBytes,
          uploadedAt: new Date().toISOString()
        }
      });

      saved.push({ name, type: file.type || "application/octet-stream", size: totalBytes, key, accessToken });
    } else {
      // Small file: inline base64.
      if (!file.data) throw new Error(`Each attachment must include file data. (${name})`);
      const buffer = Buffer.from(String(file.data), "base64");
      if (buffer.length > MAX_INLINE_BYTES) {
        throw new Error(`${name} should have been uploaded in chunks. Refresh the page and try again.`);
      }

      await store.set(key, buffer, {
        metadata: {
          accessToken,
          chunked: false,
          name,
          type: file.type || "application/octet-stream",
          size: buffer.length,
          uploadedAt: new Date().toISOString()
        }
      });

      saved.push({ name, type: file.type || "application/octet-stream", size: buffer.length, key, accessToken });
    }
  }

  return saved.map((file) => ({
    ...file,
    url: `${baseUrl}/api/download-attachment?key=${encodeURIComponent(file.key)}&t=${encodeURIComponent(file.accessToken)}`
  }));
}

export default async (request) => {
  if (request.method !== "POST") return json(405, { ok: false, error: "Method not allowed." });

  try {
    const session = await requireOfficer(request);
    const { url, token } = getBackendConfig();

    let incoming;
    try {
      incoming = JSON.parse(await request.text());
    } catch {
      return json(400, { ok: false, error: "Invalid JSON request." });
    }

    // Verified identity wins over anything the browser typed.
    if (session.enabled && session.officer) {
      const verifiedName = session.officer.name || session.officer.email;
      if (verifiedName) incoming.submittedBy = verifiedName;
      incoming.submittedByVerified = session.officer.email || session.officer.sub;
    }

    validatePayload(incoming);

    const submissionKey = `sub-${crypto.randomUUID()}`;
    const savedAttachments = await saveAttachments(request, submissionKey, incoming.attachments || []);
    const attachmentLinks = savedAttachments.map((file) => `${file.name}: ${file.url}`).join("\n");

    const payload = {
      ...incoming,
      token,
      attachments: savedAttachments.map(({ name, type, size, url: fileUrl }) => ({ name, type, size, url: fileUrl })),
      attachmentCount: savedAttachments.length,
      attachmentLinks,
      attachmentNote: incoming.attachmentNote || (savedAttachments.length ? "Files uploaded through Netlify Blobs." : "")
    };

    delete payload.formMode;
    delete payload.reportId; // Apps Script assigns the sequential PHS/DAR number.

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json" },
      body: JSON.stringify(payload)
    });

    const text = await response.text();
    let result;
    try {
      result = JSON.parse(text);
    } catch {
      return json(502, { ok: false, error: "Apps Script did not return JSON.", status: response.status });
    }

    return json(response.ok ? 200 : response.status, {
      ...result,
      attachmentsSaved: savedAttachments.length > 0,
      attachmentCount: savedAttachments.length,
      attachmentLinks: savedAttachments.map(({ name, url: fileUrl, size, type }) => ({ name, url: fileUrl, size, type }))
    });
  } catch (err) {
    return errorResponse(err);
  }
};

export const config = { path: "/api/submit-report" };
